name: pokimon
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  permission_handler: 
  http: 
  provider: 
  flutter_bloc: 
  equatable: 
  hive: 
  hive_flutter: 
  percent_indicator: 
  flex_color_scheme:
  google_fonts: ^3.0.1
  rotated_corner_decoration: ^2.0.0
  scroll_snap_list: ^0.9.1
  image_picker:


  #Firebase

  firebase_auth:
  firebase_core:
  cloud_firestore:
  flutterfire_ui:
  google_sign_in:
  sign_in_button:
  firebase_storage:
  flutter_shimmer: 

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.0
  build_runner: 
  hive_generator: 

flutter:
  
  uses-material-design: true
  
  assets:
    - assets/